config/routes.rb
Rankmaster::Application.routes.draw do |map|
  resources :awards

  resources :requirements

  resources :award_types

  resources :scouters

  resources :addresses

  resources :groups

end

app/controllers/award_types_controller.rb
class AwardTypesController < ApplicationController
  # GET /award_types
  # GET /award_types.xml
  def index
    @award_types = AwardType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @award_types }
    end
  end

  # GET /award_types/1
  # GET /award_types/1.xml
  def show
    @award_type = AwardType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @award_type }
    end
  end

  # GET /award_types/new
  # GET /award_types/new.xml
  def new
    @award_type = AwardType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @award_type }
    end
  end

  # GET /award_types/1/edit
  def edit
    @award_type = AwardType.find(params[:id])
  end

  # POST /award_types
  # POST /award_types.xml
  def create
    @award_type = AwardType.new(params[:award_type])

    respond_to do |format|
      if @award_type.save
        format.html { redirect_to(@award_type, :notice => 'AwardType was successfully created.') }
        format.xml  { render :xml => @award_type, :status => :created, :location => @award_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @award_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /award_types/1
  # PUT /award_types/1.xml
  def update
    @award_type = AwardType.find(params[:id])

    respond_to do |format|
      if @award_type.update_attributes(params[:award_type])
        format.html { redirect_to(@award_type, :notice => 'AwardType was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @award_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /award_types/1
  # DELETE /award_types/1.xml
  def destroy
    @award_type = AwardType.find(params[:id])
    @award_type.destroy

    respond_to do |format|
      format.html { redirect_to(award_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/award_types_helper.rb
module AwardTypesHelper
end

app/views/award_types/_form.html.erb
<% form_for(@award_type) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/award_types/edit.html.erb
<h1>Editing award_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @award_type %> |
<%= link_to 'Back', award_types_path %>

app/views/award_types/index.html.erb
<h1>Listing award_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @award_types.each do |award_type| %>
  <tr>
    <td><%= award_type.id %></td>
    <td><%= award_type.name %></td>
    <td><%= award_type.awards.inspect %></td>
    <td><%= link_to 'Show', award_type %></td>
    <td><%= link_to 'Edit', edit_award_type_path(award_type) %></td>
    <td><%= link_to 'Destroy', award_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New award_type', new_award_type_path %>

app/views/award_types/new.html.erb
<h1>New award_type</h1>

<%= render 'form' %>

<%= link_to 'Back', award_types_path %>

app/views/award_types/show.html.erb
<p>
  <b>Name:</b>
  <%= @award_type.name %>
</p>


<%= link_to 'Edit', edit_award_type_path(@award_type) %> |
<%= link_to 'Back', award_types_path %>