config/routes.rb
Rankmaster::Application.routes.draw do |map|
  resources :awards

  resources :requirements

  resources :award_types

  resources :scouters

  resources :addresses

  resources :groups

end

app/models/award.rb
class Award < ActiveRecord::Base
  belongs_to :award_type
  has_many :requirements
end

app/models/award_type.rb
class AwardType < ActiveRecord::Base
  has_many :awards

end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  # GET /awards
  # GET /awards.xml
  def index
    @awards = Award.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @awards }
    end
  end

  # GET /awards/1
  # GET /awards/1.xml
  def show
    @award = Award.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @award }
    end
  end

  # GET /awards/new
  # GET /awards/new.xml
  def new
    @award = Award.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @award = Award.find(params[:id])
  end

  # POST /awards
  # POST /awards.xml
  def create
    @award = Award.new(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to(@award, :notice => 'Award was successfully created.') }
        format.xml  { render :xml => @award, :status => :created, :location => @award }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @award.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.xml
  def update
    @award = Award.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to(@award, :notice => 'Award was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @award.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.xml
  def destroy
    @award = Award.find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to(awards_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<% form_for(@award) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.text_field :order %>
  </div>

  <div class="field">
    <%= f.label :award_type_id %><br />
    <%= f.text_field :award_type_id %>
  </div>

  <div class="field">
    <%= f.label :award_type %><br />
    <%= f.collection_select :award_type_id , AwardType.all, :id, :name%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing award</h1>

<%= render 'form' %>

<%= link_to 'Show', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<h1>Listing awards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Order</th>
    <th>Award type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @awards.each do |award| %>
  <tr>
    <td><%= award.name %></td>
    <td><%= award.order %></td>
    <td><%= award.award_type.name %></td>
    <td><%= link_to 'Show', award %></td>
    <td><%= link_to 'Edit', edit_award_path(award) %></td>
    <td><%= link_to 'Destroy', award, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New award', new_award_path %>

app/views/awards/new.html.erb
<h1>New award</h1>

<%= render 'form' %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p>
  <b>Name:</b>
  <%= @award.name %>
</p>

<p>
  <b>Order:</b>
  <%= @award.order %>
</p>

<p>
  <b>Award type:</b>
  <%= @award.award_type.name %>
</p>

<p>
  <b>Requirements:</b>
  <%= @award.requirements.inspect %>
</p>


<%= link_to 'Edit', edit_award_path(@award) %> |
<%= link_to 'Back', awards_path %>