config/routes.rb
Rankmaster::Application.routes.draw do |map|
  resources :awards

  resources :requirements

  resources :award_types

  resources :scouters

  resources :addresses

  resources :groups

end

app/models/scouter.rb
class Scouter < ActiveRecord::Base
  belongs_to :address
  belongs_to :group
end

app/controllers/scouters_controller.rb
class ScoutersController < ApplicationController
  # GET /scouters
  # GET /scouters.xml
  def index
    @scouters = Scouter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scouters }
    end
  end

  # GET /scouters/1
  # GET /scouters/1.xml
  def show
    @scouter = Scouter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scouter }
    end
  end

  # GET /scouters/new
  # GET /scouters/new.xml
  def new
    @scouter = Scouter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scouter }
    end
  end

  # GET /scouters/1/edit
  def edit
    @scouter = Scouter.find(params[:id])
  end

  # POST /scouters
  # POST /scouters.xml
  def create
    @scouter = Scouter.new(params[:scouter])

    respond_to do |format|
      if @scouter.save
        format.html { redirect_to(@scouter, :notice => 'Scouter was successfully created.') }
        format.xml  { render :xml => @scouter, :status => :created, :location => @scouter }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scouter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scouters/1
  # PUT /scouters/1.xml
  def update
    @scouter = Scouter.find(params[:id])

    respond_to do |format|
      if @scouter.update_attributes(params[:scouter])
        format.html { redirect_to(@scouter, :notice => 'Scouter was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scouter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scouters/1
  # DELETE /scouters/1.xml
  def destroy
    @scouter = Scouter.find(params[:id])
    @scouter.destroy

    respond_to do |format|
      format.html { redirect_to(scouters_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/scouters_helper.rb
module ScoutersHelper
end

app/views/scouters/_form.html.erb
<% form_for(@scouter) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br />
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :cell %><br />
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :address_id %><br />
    <%= f.text_field :address_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scouters/edit.html.erb
<h1>Editing scouter</h1>

<%= render 'form' %>

<%= link_to 'Show', @scouter %> |
<%= link_to 'Back', scouters_path %>

app/views/scouters/index.html.erb
<h1>Listing scouters</h1>

<table>
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Birthday</th>
    <th>Phone</th>
    <th>Cell</th>
    <th>Email</th>
    <th>Password</th>
    <th>Address</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scouters.each do |scouter| %>
  <tr>
    <td><%= scouter.first %></td>
    <td><%= scouter.last %></td>
    <td><%= scouter.birthday %></td>
    <td><%= scouter.phone %></td>
    <td><%= scouter.cell %></td>
    <td><%= scouter.email %></td>
    <td><%= scouter.password %></td>
    <td><%= scouter.address.street %></td>
    <td><%= scouter.group.name %></td>
    <td><%= link_to 'Show', scouter %></td>
    <td><%= link_to 'Edit', edit_scouter_path(scouter) %></td>
    <td><%= link_to 'Destroy', scouter, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New scouter', new_scouter_path %>

app/views/scouters/new.html.erb
<h1>New scouter</h1>

<%= render 'form' %>

<%= link_to 'Back', scouters_path %>

app/views/scouters/show.html.erb
<p>
  <b>First:</b>
  <%= @scouter.first %>
</p>

<p>
  <b>Last:</b>
  <%= @scouter.last %>
</p>

<p>
  <b>Birthday:</b>
  <%= @scouter.birthday %>
</p>

<p>
  <b>Phone:</b>
  <%= @scouter.phone %>
</p>

<p>
  <b>Cell:</b>
  <%= @scouter.cell %>
</p>

<p>
  <b>Email:</b>
  <%= @scouter.email %>
</p>

<p>
  <b>Password:</b>
  <%= @scouter.password %>
</p>

<p>
  <b>Address:</b>
  <%= @scouter.address_id %>
</p>

<p>
  <b>Group:</b>
  <%= @scouter.group_id %>
</p>


<%= link_to 'Edit', edit_scouter_path(@scouter) %> |
<%= link_to 'Back', scouters_path %>